version: '3.9'

services:
  mysql-master:
    image: 'mysql:latest'
    ports:
      - '3306:3306'
    volumes:
      - /path/to/mysql-persistence:/bitnami/mysql/data
    environment:
      - MYSQL_ROOT_PASSWORD=master_root_password
      - MYSQL_USER=my_user
      - MYSQL_PASSWORD=my_password
      - MYSQL_DATABASE=my_database
    networks:
      - my-network

volumes:
  mysql-persistence:
    driver: local

networks:
  my-network:
    driver: bridge
